# Generated by Django 5.0.7 on 2024-08-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_order_is_removed_products_is_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='inventory',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
